version: '3.9'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot_container2
    restart: always
    env_file:
      - ./.env
    depends_on:
      - redis
    volumes:
      - .:/app
    command: ["python3", "main.py"]

  redis:
    image: redis:latest
    container_name: redis_container2
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
  redis_data:

